### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by xiaozhangtongx** [Database-and-Big-Data-Analytics-Lab/E2DTC#1]
Dear ZJU-DAILY, I was looking at your code recently, and I found that you only talked about how to train the model here. So how can I refer to this model in our actual GPS data? Looking forward to your reply. Thanks!!!

**Comment by xiaozhangtongx** [comment]
Also, Dear ZJU-DAILY， can you share how the file `data/trj_vocab.h5` is generated? thank you very much!

**Comment by yuntaod** [comment]
Hi,

Thanks for your question. You can convert the GPS points to token vocabulary by griding the map into discrete cells. You can find the details in [t2vec](https://github.com/boathit/t2vec).

Hope it helps.
